// <auto-generated />
using System;
using Diary_Proj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Diary_Proj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200120010740_ChangePicPath")]
    partial class ChangePicPath
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Diary_Proj.Models.DayNote", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE");

                    b.HasKey("Date");

                    b.ToTable("DayNotes");
                });

            modelBuilder.Entity("Diary_Proj.Models.Note", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_FK")
                        .HasColumnName("Date")
                        .HasColumnType("DATE");

                    b.Property<string>("Pic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("StartAt")
                        .HasColumnType("time");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Date_FK");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Diary_Proj.Models.Note", b =>
                {
                    b.HasOne("Diary_Proj.Models.DayNote", "DayNote")
                        .WithMany("Notes")
                        .HasForeignKey("Date_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
